export const ACTION_TYPES = {
    ADD_NOTE: 'ADD_NOTE',
    REMOVE_NOTE: 'REMOVE_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
    SEARCH_NOTE: 'SEARCH_NOTE',
    ADD_COLOR: 'ADD_COLOR'
};

export const STORAGE_KEY = 'NOTES-APP';